name = "wondlo"
compatibility_date = "2024-01-01"

[vars]
NODE_ENV = "production"

[env.production]
vars = { NODE_ENV = "production" }

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "wondlo-assets"